// This file defines common grading systems and possible values for those systems
// Many of the enumerations were generated by ChatGPT

export type Grade = BoulderGrade|RopeGrade|NA;

export type NA = "N/A"
export type BoulderGrade = VScale;
export type RopeGrade = Ewbank|YDS;


export enum BoulderGradeScale {
    VScale = "V-Scale",
    //FontScale = "Font. Scale",
}
export enum RopeGradeScale {
    Ewbank = "Ewbank Scale",
    YDS = "Yosemite Decimal System",
    //FrenchScale = "French Scale",
}

// BOULDER GRADING SCALES
    // V-Scale (Boulders - Global)
    export type VScale = {
        type: BoulderGradeScale.VScale
        value: VScaleValues
    }
    export enum VScaleValues {
        "VB-" = "VB-",
        "VB" = "VB",
        "VB+" = "VB+",
        "V0-" = "V0-",
        "V0" = "V0",
        "V0+" = "V0+",
        "V1" = "V1",
        "V2" = "V2",
        "V3" = "V3",
        "V4" = "V4",
        "V5" = "V5",
        "V6" = "V6",
        "V7" = "V7",
        "V8" = "V8",
        "V9" = "V9",
        "V10" = "V10",
        "V11" = "V11",
        "V12" = "V12",
        "V13" = "V13",
        "V14" = "V14",
        "V15" = "V15",
        "V16" = "V16",
        "V17" = "V17"
    }
    

// ROPE GRADING SCALES
    // Ewbank Scale (AU/NZ)
    export type Ewbank = {
        type: RopeGradeScale.Ewbank,
        value: EwbankValues
    }
    export enum EwbankValues {
        Number1 = "1",
        Number2 = "2",
        Number3 = "3",
        Number4 = "4",
        Number5 = "5",
        Number6 = "6",
        Number7 = "7",
        Number8 = "8",
        Number9 = "9",
        Number10 = "10",
        Number11 = "11",
        Number12 = "12",
        Number13 = "13",
        Number14 = "14",
        Number15 = "15",
        Number16 = "16",
        Number17 = "17",
        Number18 = "18",
        Number19 = "19",
        Number20 = "20",
        Number21 = "21",
        Number22 = "22",
        Number23 = "23",
        Number24 = "24",
        Number25 = "25",
        Number26 = "26",
        Number27 = "27",
        Number28 = "28",
        Number29 = "29",
        Number30 = "30",
        Number31 = "31",
        Number32 = "32",
        Number33 = "33",
        Number34 = "34",
        Number35 = "35",
        Number36 = "36",
        Number37 = "37",
        Number38 = "38",
        Number39 = "39",
        Number40 = "40", 
    }


    // Yosemite Decimal Scale (US)
    export type YDS = {
        type: RopeGradeScale.YDS,
        value: YDSValues,
    }
    export enum YDSValues {
        "3-4" = "3-4",
        "5.0" = "5.0",
        "5.1_" = "5.1",
        "5.2_" = "5.2",
        "5.3_" = "5.3",
        "5.4_" = "5.4",
        "5.5_" = "5.5",
        "5.6_" = "5.6",
        "5.7_" = "5.7",
        "5.8_" = "5.8",
        "5.9_" = "5.9",
        "5.10a" = "5.10a",
        "5.10b" = "5.10b",
        "5.10c" = "5.10c",
        "5.10d" = "5.10d",
        "5.11a" = "5.11a",
        "5.11b" = "5.11b",
        "5.11c" = "5.11c",
        "5.11d" = "5.11d",
        "5.12a" = "5.12a",
        "5.12b" = "5.12b",
        "5.12c" = "5.12c",
        "5.12d" = "5.12d",
        "5.13a" = "5.13a",
        "5.13b" = "5.13b",
        "5.13c" = "5.13c",
        "5.13d" = "5.13d",
        "5.14a" = "5.14a",
        "5.14b" = "5.14b",
        "5.14c" = "5.14c",
        "5.14d" = "5.14d",
        "5.15a" = "5.15a",
        "5.15b" = "5.15b",
        "5.15c" = "5.15c",
        "5.15d" = "5.15d"
    }
    
export const ScaleToGrades = {
    "V-Scale" : VScaleValues,
    "Ewbank Scale" : EwbankValues,
    "Yosemite Decimal System": YDSValues
}
